name: Keep Render Alive

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render Health Endpoint
        run: |
          curl -L https://futuredekho-server.onrender.com/docs